name: Deploy FastAPI to Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AZURE_WEBAPP_NAME: soporteit-tfmii
  PYTHON_VERSION: '3.12'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create package for Azure
        run: |
          pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          echo "SCM_DO_BUILD_DURING_DEPLOYMENT=true" >> $GITHUB_ENV
          zip -r app.zip . -x "*.git*"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A96C11157EBC4CF78A67E2FF69F174F9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E9D577A04FB94B24AD3CFABD895D2252 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_816FE729E6F343888BCB0A8A1A09BD3B }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: app.zip